In [3]:
!pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1324 sha256=7f02a46f3df986b102796af1ccdb100421c04b7f631cd756f6b39b9a76955716
  Stored in directory: C:\Users\asiddiqui\AppData\Local\pip\Cache\wheels\76\03\bb\589d421d27431bcd2c6da284d5f2286c8e3b2ea3cf1594c074
Successfully built sklearn


You should consider upgrading via the 'python -m pip install --upgrade pip' command.


# Classfication

In [1]:
#imports
#numpy, pandas, math, math plotlib
import numpy as np
import pandas as pd
import scipy
from math import sqrt
import matplotlib.pyplot as plt

#estimators
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import linear_model

#model metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#cross validation
from sklearn.model_selection import train_test_split

# Import File and Change Data Type

In [2]:
#data
rawData = pd.read_csv('default of credit card clients.csv', header=1, dtype={
                     'SEX': 'category',
                     'EDUCATION': 'category',
                     'MARRIAGE': 'category',
                     'PAY_0': 'category',
                     'PAY_2': 'category',
                     'PAY_3': 'category',
                     'PAY_4': 'category',
                     'PAY_5': 'category',
                     'PAY_6': 'category',
                    'default payment next month': 'bool'} )
rawData.head()

rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
ID                            30000 non-null int64
LIMIT_BAL                     30000 non-null int64
SEX                           30000 non-null category
EDUCATION                     30000 non-null category
MARRIAGE                      30000 non-null category
AGE                           30000 non-null int64
PAY_0                         30000 non-null category
PAY_2                         30000 non-null category
PAY_3                         30000 non-null category
PAY_4                         30000 non-null category
PAY_5                         30000 non-null category
PAY_6                         30000 non-null category
BILL_AMT1                     30000 non-null int64
BILL_AMT2                     30000 non-null int64
BILL_AMT3                     30000 non-null int64
BILL_AMT4                     30000 non-null int64
BILL_AMT5                     30000 non-null int

In [3]:
##--------Classification-----------##

#features
#Remove ID Feature
featuresClass = rawData.iloc[:,1:25]
print('Summary of feature sample')
featuresClass.head()

Summary of feature sample


LIMIT_BAL SEX EDUCATION MARRIAGE  AGE PAY_0 PAY_2 PAY_3 PAY_4 PAY_5  \
0      20000   2         2        1   24     2     2    -1    -1    -2   
1     120000   2         2        2   26    -1     2     0     0     0   
2      90000   2         2        2   34     0     0     0     0     0   
3      50000   2         2        1   37     0     0     0     0     0   
4      50000   1         2        1   57    -1     0    -1     0     0   

              ...             BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0             ...                     0          0          0         0   
1             ...                  3272       3455       3261         0   
2             ...                 14331      14948      15549      1518   
3             ...                 28314      28959      29547      2000   
4             ...                 20940      19146      19131      2000   

   PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0       689         0         0         0         0   
1      1000      1000      1000         0      2000   
2      1500      1000      1000      1000      5000   
3      2019      1200      1100      1069      1000   
4     36681     10000      9000       689       679   

   default payment next month  
0                        True  
1                        True  
2                       False  
3                       False  
4                       False  

[5 rows x 24 columns]

In [4]:
#dependent variable
depVarClass = rawData['default payment next month']

# Feature Selection

In [5]:
##OOB##

OOB = featuresClass
OOBdepvar = depVarClass

# Create Dummy Variables for Category Data

In [7]:
OOB = pd.get_dummies(OOB)
OOB.head()

LIMIT_BAL  AGE  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
0      20000   24       3913       3102        689          0          0   
1     120000   26       2682       1725       2682       3272       3455   
2      90000   34      29239      14027      13559      14331      14948   
3      50000   37      46990      48233      49291      28314      28959   
4      50000   57       8617       5670      35835      20940      19146   

   BILL_AMT6  PAY_AMT1  PAY_AMT2   ...     PAY_6_-1  PAY_6_-2  PAY_6_0  \
0          0         0       689   ...            0         1        0   
1       3261         0      1000   ...            0         0        0   
2      15549      1518      1500   ...            0         0        1   
3      29547      2000      2019   ...            0         0        1   
4      19131      2000     36681   ...            0         0        1   

   PAY_6_2  PAY_6_3  PAY_6_4  PAY_6_5  PAY_6_6  PAY_6_7  PAY_6_8  
0        0        0        0        0        0        0        0  
1        1        0        0        0        0        0        0  
2        0        0        0        0        0        0        0  
3        0        0        0        0        0        0        0  
4        0        0        0        0        0        0        0  

[5 rows x 92 columns]

# Training & Testing 

In [8]:
###OOB###

#Training Set (Feature Space: X Training)
X_train_OOB = (OOB[: 1000])
X_train_OOB.head()

#Dependent Variable Training Set (y Training)
y_train_OOB = OOBdepvar[: 1000]
y_train_OOB_count = len(y_train_OOB.index)
print('The number of observations in the Y training set are:',str(y_train_OOB_count))
y_train_OOB.head()

#Testing Set (X Testing)
X_test_OOB = OOB[-100:]
X_test_OOB_count = len(X_test_OOB.index)
print('The number of observations in the feature testing set is:',str(X_test_OOB_count))
print(X_test_OOB.head())

#Ground Truth (y_test) 
y_test_OOB = OOBdepvar[-100:]
y_test_OOB_count = len(y_test_OOB.index)
print('The number of observations in the Y training set are:',str(y_test_OOB_count))
y_test_OOB.head()

The number of observations in the Y training set are: 1000
The number of observations in the feature testing set is: 100
       LIMIT_BAL  AGE  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
29900      20000   29      16809          0          0          0          0   
29901      50000   29      50845      48750     103486      50590      50248   
29902     170000   30      10392     168088     168955     161351     126198   
29903     260000   30      27378      17082      13333         99         99   
29904      60000   30      54952      56021      54126      58732      59306   

       BILL_AMT6  PAY_AMT1  PAY_AMT2   ...     PAY_6_-1  PAY_6_-2  PAY_6_0  \
29900          0         0         0   ...            0         1        0   
29901      49387         0      6556   ...            0         0        1   
29902     124746    168096      6409   ...            0         0        1   
29903     172104     10018     13333   ...            1         0        0   
29904   

29900     True
29901    False
29902    False
29903    False
29904     True
Name: default payment next month, dtype: bool

# Cross Validation

In [39]:
##OOB
from sklearn.model_selection import train_test_split

X_train_OOB, X_test_OOB, y_train_OOB, y_test_OOB = train_test_split(X_train_OOB, y_train_OOB)

# Model Selection - OOB

# Model: SVC

In [40]:
#Models
from sklearn.svm import LinearSVC


#LinearSVC().get_params()

In [41]:
#Model Fitting SVC - Default
modelLSVC = LinearSVC()
modelLSVC.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelLSVC, X_train_OOB, y_train_OOB,cv=3))
modelLSVC.score(X_train_OOB,y_train_OOB)

Dep_pred = modelLSVC.predict(X_test_OOB)
acc = accuracy_score(y_test_OOB, Dep_pred)
print(cross_val_score(modelLSVC, X_train_OOB, y_train_OOB))
print("Test set accuracy: {:.2f}".format(acc))
print(classification_report(y_test_OOB, Dep_pred))

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program F

[0.78723404 0.78609626 0.78074866]
[0.78761062 0.69911504 0.71428571 0.78571429 0.59821429]
Test set accuracy: 0.77
              precision    recall  f1-score   support

       False       0.79      0.95      0.87       149
        True       0.22      0.05      0.08        39

    accuracy                           0.77       188
   macro avg       0.51      0.50      0.47       188
weighted avg       0.67      0.77      0.70       188



C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [42]:
#Model Fitting SVC, max iter = 2
modelLSVC2 = LinearSVC(max_iter = 2)
modelLSVC2.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelLSVC2, X_train_OOB, y_train_OOB,cv=3))
modelLSVC2.score(X_train_OOB,y_train_OOB)

Dep_pred = modelLSVC2.predict(X_test_OOB)
acc = accuracy_score(y_test_OOB, Dep_pred)
print(cross_val_score(modelLSVC2, X_train_OOB, y_train_OOB))
print("Test set accuracy: {:.2f}".format(acc))
print(classification_report(y_test_OOB, Dep_pred))

[0.78723404 0.59893048 0.78609626]
[0.78761062 0.77876106 0.44642857 0.55357143 0.78571429]
Test set accuracy: 0.52
              precision    recall  f1-score   support

       False       0.86      0.46      0.60       149
        True       0.26      0.72      0.38        39

    accuracy                           0.52       188
   macro avg       0.56      0.59      0.49       188
weighted avg       0.74      0.52      0.56       188



C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program F

In [43]:
#Model Fitting Random Forest, max iter = 4
modelLSVC4 = LinearSVC(max_iter = 4)
modelLSVC4.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelLSVC4, X_train_OOB, y_train_OOB,cv=3))
modelLSVC4.score(X_train_OOB,y_train_OOB)

Dep_pred = modelLSVC4.predict(X_test_OOB)
acc = accuracy_score(y_test_OOB, Dep_pred)
print(cross_val_score(modelLSVC4, X_train_OOB, y_train_OOB))
print("Test set accuracy: {:.2f}".format(acc))
print(classification_report(y_test_OOB, Dep_pred))

[0.78191489 0.63636364 0.78074866]
[0.78761062 0.24778761 0.78571429 0.78571429 0.75892857]
Test set accuracy: 0.79
              precision    recall  f1-score   support

       False       0.79      1.00      0.88       149
        True       0.00      0.00      0.00        39

    accuracy                           0.79       188
   macro avg       0.40      0.50      0.44       188
weighted avg       0.63      0.79      0.70       188



C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program F

# Model: KNN

In [15]:
from sklearn.neighbors import KNeighborsClassifier
modelKNN = KNeighborsClassifier()

In [16]:
#Model Fitting KNN - Default
modelKNN.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelKNN, X_train_OOB, y_train_OOB,cv=3))
modelKNN.score(X_train_OOB,y_train_OOB)

Dep_pred = modelKNN.predict(X_test_OOB)
acc = accuracy_score(y_test_OOB, Dep_pred)
print(cross_val_score(modelKNN, X_train_OOB, y_train_OOB))
print("Test set accuracy: {:.2f}".format(acc))
print(classification_report(y_test_OOB, Dep_pred))

[0.756 0.744 0.72 ]
[0.7        0.77333333 0.72       0.7        0.72      ]
Test set accuracy: 0.77
              precision    recall  f1-score   support

       False       0.80      0.94      0.86       196
        True       0.39      0.13      0.19        54

    accuracy                           0.77       250
   macro avg       0.59      0.54      0.53       250
weighted avg       0.71      0.77      0.72       250



In [17]:
#KNN Neighbors 3
modelKNN3 = KNeighborsClassifier(n_neighbors=3)
modelKNN3.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelKNN3, X_train_OOB, y_train_OOB,cv=3))
modelKNN3.score(X_train_OOB,y_train_OOB)

Dep_pred = modelKNN3.predict(X_test_OOB)
acc = accuracy_score(y_test_OOB, Dep_pred)
print(cross_val_score(modelKNN3, X_train_OOB, y_train_OOB))
print("Test set accuracy: {:.2f}".format(acc))
print(classification_report(y_test_OOB, Dep_pred))

[0.736 0.688 0.716]
[0.72666667 0.76       0.69333333 0.68       0.72666667]
Test set accuracy: 0.74
              precision    recall  f1-score   support

       False       0.80      0.88      0.84       196
        True       0.34      0.22      0.27        54

    accuracy                           0.74       250
   macro avg       0.57      0.55      0.56       250
weighted avg       0.70      0.74      0.72       250



In [18]:
#KNN Neighbors 5
modelKNN5 = KNeighborsClassifier(n_neighbors=5)
modelKNN5.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelKNN5, X_train_OOB, y_train_OOB,cv=3))
modelKNN5.score(X_train_OOB,y_train_OOB)

Dep_pred = modelKNN5.predict(X_test_OOB)
acc = accuracy_score(y_test_OOB, Dep_pred)
print(cross_val_score(modelKNN5, X_train_OOB, y_train_OOB))
print("Test set accuracy: {:.2f}".format(acc))
print(classification_report(y_test_OOB, Dep_pred))

[0.756 0.744 0.72 ]
[0.7        0.77333333 0.72       0.7        0.72      ]
Test set accuracy: 0.77
              precision    recall  f1-score   support

       False       0.80      0.94      0.86       196
        True       0.39      0.13      0.19        54

    accuracy                           0.77       250
   macro avg       0.59      0.54      0.53       250
weighted avg       0.71      0.77      0.72       250



# Model: Decision Tree

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
# Decision Tree Default
modelDT = DecisionTreeClassifier()

#Model Fitting Random Forest
modelDT.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelDT, X_train_OOB, y_train_OOB,cv=3))
modelDT.score(X_train_OOB,y_train_OOB)

Dep_pred = modelDT.predict(X_test_OOB)
acc = accuracy_score(y_test_OOB, Dep_pred)
print(cross_val_score(modelDT, X_train_OOB, y_train_OOB))
print("Test set accuracy: {:.2f}".format(acc))
print(classification_report(y_test_OOB, Dep_pred))

[1. 1. 1.]
[1. 1. 1. 1. 1.]
Test set accuracy: 1.00
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       196
        True       1.00      1.00      1.00        54

    accuracy                           1.00       250
   macro avg       1.00      1.00      1.00       250
weighted avg       1.00      1.00      1.00       250



In [21]:
# Decision Tree RS = 2
modelDT2 = DecisionTreeClassifier(random_state=2)

#Model Fitting Random Forest
modelDT2.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelDT2, X_train_OOB, y_train_OOB,cv=3))
modelDT2.score(X_train_OOB,y_train_OOB)

Dep_pred = modelDT2.predict(X_test_OOB)
acc = accuracy_score(y_test_OOB, Dep_pred)
print(cross_val_score(modelDT2, X_train_OOB, y_train_OOB))
print("Test set accuracy: {:.2f}".format(acc))
print(classification_report(y_test_OOB, Dep_pred))

[1. 1. 1.]
[1. 1. 1. 1. 1.]
Test set accuracy: 1.00
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       196
        True       1.00      1.00      1.00        54

    accuracy                           1.00       250
   macro avg       1.00      1.00      1.00       250
weighted avg       1.00      1.00      1.00       250



In [22]:
# Decision Tree RS = 4
modelDT4 = DecisionTreeClassifier(random_state=4)

#Model Fitting Random Forest
modelDT4.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelDT4, X_train_OOB, y_train_OOB,cv=3))
modelDT4.score(X_train_OOB,y_train_OOB)

Dep_pred = modelDT4.predict(X_test_OOB)
acc = accuracy_score(y_test_OOB, Dep_pred)
print(cross_val_score(modelDT4, X_train_OOB, y_train_OOB))
print("Test set accuracy: {:.2f}".format(acc))
print(classification_report(y_test_OOB, Dep_pred))

[1. 1. 1.]
[1. 1. 1. 1. 1.]
Test set accuracy: 1.00
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       196
        True       1.00      1.00      1.00        54

    accuracy                           1.00       250
   macro avg       1.00      1.00      1.00       250
weighted avg       1.00      1.00      1.00       250



# Feature Selection - RFE

In [35]:
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.feature_selection import RFE
import matplotlib.pyplot as plt
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC

#RFE Knn
Knn = KNeighborsClassifier(n_neighbors=5)

rfe = RFE(Knn, n_features_to_select=3)

rfe.fit(X_train_OOB, y_train_OOB)

#print(np.mean(cross_val_score(rfe, X_train_OOB, y_train_OOB, cv=3)))

#y_pred = rfe.predict(X_test_OOB)
#acc6 = accuracy_score(y_test_OOB, y_pred)
#print("Test set accuracy: {:.2f}".format(acc6))

#print(classification_report(y_test_OOB, y_pred))

RuntimeError: The classifier does not expose "coef_" or "feature_importances_" attributes

In [44]:
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.feature_selection import RFE
import matplotlib.pyplot as plt
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC

#RFE Knn
LSVC4 = LinearSVC(max_iter = 4)

rfe = RFE(LSVC4, n_features_to_select=3)

rfe.fit(X_train_OOB, y_train_OOB)

print(np.mean(cross_val_score(rfe, X_train_OOB, y_train_OOB, cv=3)))

y_pred = rfe.predict(X_test_OOB)
acc6 = accuracy_score(y_test_OOB, y_pred)
print("Test set accuracy: {:.2f}".format(acc6))

print(classification_report(y_test_OOB, y_pred))


C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program F

0.617504835589942
Test set accuracy: 0.77
              precision    recall  f1-score   support

       False       0.80      0.94      0.87       149
        True       0.36      0.13      0.19        39

    accuracy                           0.77       188
   macro avg       0.58      0.53      0.53       188
weighted avg       0.71      0.77      0.73       188



C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program F

In [45]:
print(ranking)

NameError: name 'ranking' is not defined

# Selected Model Linear SVC

In [46]:
#y_test_OOB
X_test_OOB
PredSample = X_test_OOB
PredSample['y'] = y_test_OOB
PredSample['Pred'] = Dep_pred
#print(PredSample)
PredSample

LIMIT_BAL  AGE  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
739      80000   25      17330      19258      23416      22768      23243   
847      50000   42      47647      50232      50510      32177      29530   
242      50000   27      26655      27724      28676      27990      28790   
535      60000   25        480       1675       3630        578       4825   
169      50000   22      28040      29092      29366      27737      28318   
9        20000   35          0          0          0          0      13007   
649      20000   46      21075      20795      20206      19617      18737   
260     510000   29      78331      99414     107686     103776      87265   
313     200000   49      52439      51040      56205      54723      58657   
97      150000   27      86009      86108      89006      89775      87725   
66       10000   56       2097       4193       3978       4062       4196   
511     120000   35        240        240        240        240        240   
76       50000   25      42838      37225      36087       9636       9590   
298     280000   36      58983      60788      63225      29701      30172   
269      50000   27      13694      14880      14242      13968      14319   
407     500000   37     507062     491956     430637     376657     356636   
967     220000   36        996       4102       4111       1057        990   
660     160000   33      14150       8106      12431      12145      13391   
846     300000   34     205064        -86        -86       2014       -185   
32      100000   32      93036      84071      82880      80958      78703   
181      80000   35      49608      12412      14873      17364      17770   
941      50000   44       1261       1261       1261       1261       1261   
784     230000   32      87764      73526      72376      76870      75211   
218     110000   31      89989      84229      79288      73315      63818   
737     610000   31     142764     126606      67887      58397     105301   
503     130000   33      19161      20544      22704      22304      22304   
174     360000   29          0          0         77          0          0   
887     180000   30       2488      13476       3173      13202       6594   
355     180000   45      27679      28422      29650      29981      30419   
421     440000   29     169661     167199     158520     156977     157963   
..         ...  ...        ...        ...        ...        ...        ...   
586     220000   43          0          0          0          0          0   
45      210000   29          0          0          0          0          0   
590     230000   30      30341      25981      24092      65840      56538   
771     260000   44        316        316        316        316        316   
596     360000   29     268112     263368     259969     255832     245462   
696      50000   34      27966      28539      11597       6611       7349   
457      50000   32      23974      24131      25326      25775          0   
183      60000   24      58024      57891      48839      18971      19323   
561     360000   52        640       2113         -6        999        944   
494      80000   28       8574       9434      10038      10040      10400   
217      80000   36      79278      78501      78534      80016      76235   
879      20000   43      15294      16340      17359      17776      19293   
259     220000   48     210380     213522     201852     169115     172169   
772      20000   33      11026       9535      10510      10472      10140   
94       60000   23      45648      46850      47214      19595      19209   
746      50000   34      10821      11877      13656      14949      16567   
232      50000   26     102800          0          0       2624      45567   
763      90000   29      19450       3123       2121       3113          0   
603     140000   28      26450      28823      28171      28740      30454   
601      30000   59        