In [3]:
!pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1324 sha256=7f02a46f3df986b102796af1ccdb100421c04b7f631cd756f6b39b9a76955716
  Stored in directory: C:\Users\asiddiqui\AppData\Local\pip\Cache\wheels\76\03\bb\589d421d27431bcd2c6da284d5f2286c8e3b2ea3cf1594c074
Successfully built sklearn


You should consider upgrading via the 'python -m pip install --upgrade pip' command.


# Classfication

In [2]:
#imports
#numpy, pandas, math, math plotlib
import numpy as np
import pandas as pd
import scipy
from math import sqrt
import matplotlib.pyplot as plt

#estimators
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import linear_model

#model metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#cross validation
from sklearn.model_selection import train_test_split

In [3]:
#data
rawData = pd.read_csv('default of credit card clients.csv', header=1)
rawData.head()

rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
ID                            30000 non-null int64
LIMIT_BAL                     30000 non-null int64
SEX                           30000 non-null int64
EDUCATION                     30000 non-null int64
MARRIAGE                      30000 non-null int64
AGE                           30000 non-null int64
PAY_0                         30000 non-null int64
PAY_2                         30000 non-null int64
PAY_3                         30000 non-null int64
PAY_4                         30000 non-null int64
PAY_5                         30000 non-null int64
PAY_6                         30000 non-null int64
BILL_AMT1                     30000 non-null int64
BILL_AMT2                     30000 non-null int64
BILL_AMT3                     30000 non-null int64
BILL_AMT4                     30000 non-null int64
BILL_AMT5                     30000 non-null int64
BILL_AMT6               

In [4]:
##--------Classification-----------##

#features
#Remove ID Feature
featuresClass = rawData.iloc[:,1:25]
print('Summary of feature sample')
featuresClass.head()

Summary of feature sample


LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57     -1      0     -1      0   

   PAY_5             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0     -2             ...                      0          0          0   
1      0             ...                   3272       3455       3261   
2      0             ...                  14331      14948      15549   
3      0             ...                  28314      28959      29547   
4      0             ...                  20940      19146      19131   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         0       689         0         0         0         0   
1         0      1000      1000      1000         0      2000   
2      1518      1500      1000      1000      1000      5000   
3      2000      2019      1200      1100      1069      1000   
4      2000     36681     10000      9000       689       679   

   default payment next month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0  

[5 rows x 24 columns]

In [8]:
#dependent variable
depVarClass = rawData['default payment next month']

# Feature Selection

In [9]:
##OOB##
OOB = featuresClass
OOBdepvar = depVarClass

# Training & Testing 

In [11]:
###OOB###

#Training Set (Feature Space: X Training)
X_train_OOB = (OOB[: 1000])
X_train_OOB.head()

#Dependent Variable Training Set (y Training)
y_train_OOB = OOBdepvar[: 1000]
y_train_OOB_count = len(y_train_OOB.index)
print('The number of observations in the Y training set are:',str(y_train_OOB_count))
y_train_OOB.head()

#Testing Set (X Testing)
X_test_OOB = OOB[-100:]
X_test_OOB_count = len(X_test_OOB.index)
print('The number of observations in the feature testing set is:',str(X_test_OOB_count))
print(X_test_OOB.head())

#Ground Truth (y_test) 
y_test_OOB = OOBdepvar[-100:]
y_test_OOB_count = len(y_test_OOB.index)
print('The number of observations in the Y training set are:',str(y_test_OOB_count))
y_test_OOB.head()

The number of observations in the Y training set are: 1000
The number of observations in the feature testing set is: 100
       LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
29900      20000    1          2         2   29      0      0     -2     -2   
29901      50000    1          2         2   29      1      2      0      0   
29902     170000    1          3         2   30      0     -1      0      0   
29903     260000    1          1         1   30     -1      0     -1     -1   
29904      60000    1          3         2   30      0      0      0      0   

       PAY_5             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
29900     -2             ...                      0          0          0   
29901      0             ...                  50590      50248      49387   
29902      0             ...                 161351     126198     124746   
29903     -1             ...                     99         99     172104   
29904      0       

29900    1
29901    0
29902    0
29903    0
29904    1
Name: default payment next month, dtype: int64

# Cross Validation

In [12]:
##OOB
from sklearn.model_selection import train_test_split

X_train_OOB, X_test_OOB, y_train_OOB, y_test_OOB = train_test_split(X_train_OOB, y_train_OOB)

# Model Selection

# Model Selection - OOB

In [13]:
#Models
from sklearn.svm import LinearSVC

modelLSVC = LinearSVC()
LinearSVC().get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': True,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'loss': 'squared_hinge',
 'max_iter': 1000,
 'multi_class': 'ovr',
 'penalty': 'l2',
 'random_state': None,
 'tol': 0.0001,
 'verbose': 0}

In [14]:
#Model Fitting Random Forest
modelLSVC.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelLSVC, X_train_OOB, y_train_OOB,cv=3))
modelLSVC.score(X_train_OOB,y_train_OOB)

[0.728 0.788 0.764]


C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.48933333333333334

In [15]:
from sklearn.neighbors import KNeighborsClassifier
modelKNN = KNeighborsClassifier()

In [16]:
#Model Fitting Random Forest
modelKNN.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelKNN, X_train_OOB, y_train_OOB,cv=3))
modelKNN.score(X_train_OOB,y_train_OOB)

[0.76  0.724 0.708]


0.8173333333333334

In [17]:
from sklearn.tree import DecisionTreeClassifier
modelDT = DecisionTreeClassifier()

#Model Fitting Random Forest
modelDT.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelDT, X_train_OOB, y_train_OOB,cv=3))
modelDT.score(X_train_OOB,y_train_OOB)

[1. 1. 1.]


1.0

# Model Selection - RFE

In [ ]:
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.feature_selection import RFE
import matplotlib.pyplot as plt

# Create the RFE object and rank each pixel
svc = SVC(kernel="linear", C=1)
rfe = RFE(estimator=svc, n_features_to_select=1, step=1)
selectedfeatures = rfe.fit(X_train_OOB, y_train_OOB)
ranking = selectedfeatures.ranking

In [ ]:
print(ranking)

# Selected Model KNN

In [46]:
from sklearn.neighbors import KNeighborsClassifier
modelKNN = KNeighborsClassifier()

#Model Fitting Random Forest
modelKNN.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelKNN, X_train_OOB, y_train_OOB,cv=3))
modelKNN.score(X_train_OOB,y_train_OOB)


[0.732 0.748 0.756]


0.8226666666666667

In [47]:
modelKNN_5 = KNeighborsClassifier(n_neighbors=3)

modelKNN_5.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelKNN_5, X_train_OOB, y_train_OOB,cv=3))
modelKNN_5.score(X_train_OOB,y_train_OOB)

[0.696 0.74  0.716]


0.8453333333333334

In [29]:
modelKNN_5 = KNeighborsClassifier(n_neighbors=6)

modelKNN_5.fit(X_train_OOB,y_train_OOB)
print(cross_val_score(modelKNN_5, X_train_OOB, y_train_OOB,cv=3))
modelKNN_5.score(X_train_OOB,y_train_OOB)

[0.768 0.784 0.788]


0.808

In [48]:
predictions = modelKNN_5.predict(X_test_OOB)

In [51]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from math import sqrt

predRsquared = r2_score(y_test_OOB,predictions)
rmse = sqrt(mean_squared_error(y_test_OOB, predictions))
print('R Squared: %.3f' % predRsquared)
print('RMSE: %.3f' % rmse)

R Squared: -0.673
RMSE: 0.559


In [50]:
#y_test_OOB
X_test_OOB
PredSample = X_test_OOB
PredSample['Pred'] = predictions
#print(PredSample)
PredSample

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
935      50000    1          2         2   30      0      0      0      0   
20      130000    2          3         2   39      0      0      0      0   
691     170000    1          2         2   27     -1      2      2     -2   
970     300000    1          1         1   42     -1      0      0     -1   
70       80000    1          1         2   31     -1     -1     -1     -1   
673      30000    1          2         2   25      2      2      7      7   
684     320000    1          1         1   40      0      0      0      0   
470     390000    2          3         2   35      0      0      0      0   
718     150000    2          1         1   35      1     -2     -2     -2   
483      90000    1          3         1   48      1      2      2      2   
676     190000    1          2         2   40      2      2      2      2   
472     180000    1          2         1   34     -1     -1     -1     -1   
938     180000    2          2         1   32      1      2      2      2   
269      50000    1          2         2   27      3      2      2      0   
237     210000    2          1         2   31     -2     -2     -2     -2   
297     210000    2          2         1   36      0      0      0      0   
779      50000    2          2         2   31      1     -2     -1     -1   
726     360000    2          2         2   39     -1     -1     -1      0   
999     120000    1          2         2   25      2      2      0      0   
352     380000    1          1         2   30      1     -2     -2     -2   
817      20000    2          3         2   24     -1     -1     -1     -1   
670      30000    2          2         2   34      2     -1      2      2   
474     120000    2          2         1   32     -1     -1     -1     -1   
234      60000    2          2         1   33      0      0      0      0   
216     240000    2          2         1   36      1     -2     -2     -2   
294     130000    1          1         2   29      1     -2     -2     -2   
571      50000    2          2         2   23      0      0      0      0   
931     320000    1          1         1   60     -1     -1     -1     -1   
324     360000    2          2         2   32      0      0      0      0   
864     200000    1          1         2   32      0      0      0      0   
..         ...  ...        ...       ...  ...    ...    ...    ...    ...   
490      90000    2          2         2   32     -2     -2     -2     -2   
895     200000    1          1         2   31     -2     -2     -2     -2   
440      50000    1          2         2   23     -1     -1     -1     -1   
395     140000    2          1         2   27      0      0      0      0   
45      210000    1          1         2   29     -2     -2     -2     -2   
232      50000    1          2         1   26      0      0     -2     -1   
453     200000    2          1         2   26      0      0     -2     -2   
892      80000    2          2         1   32      0      0      0      0   
501      90000    2          2         1   35      1      2      2      2   
701     200000    2          1         1   27     -1     -1     -1     -1   
266      10000    1          3         2   23      0      0      0      0   
881     210000    2          2         1   49      1     -2     -2     -2   
576     270000    2          1         2   28     -1     -1     -1      0   
393     140000    2          2         2   29      0      0      0      0   
345     160000    2          1         2   29     -1     -1     -2     -1   
499      20000    1          1         1   38      0      0      0      2   
816      70000    1          3         1   51      2      2      0      0   
93      160000    2          2         1   37     -1     -1     -1     -1   
774      50000    2          1         2   33     -1      2     -1     -1   
62       50000    1          1         2   29      2      2      2      2   
5